name: internshala
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  dio: ^5.6.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_gen: ^5.6.0
  path_provider: ^2.1.4
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  talker_dio_logger: ^4.4.1
  velocity_x: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_gen_runner: ^5.6.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/svgs/

