import 'package:internshala/ui/views/filter/model/check_box_model.dart';
import 'package:internshala/ui/views/filter/model/monthly_stipend_model.dart';


List<CheckBoxModel> internshipsTypeList = [
    CheckBoxModel(id: 1, isChecked: false, fieldName: "Work from home"),
    CheckBoxModel(id: 2, isChecked: false, fieldName: "Part-time")
];

List<MonthlyStipendModel> monthlyStipendsList = [
    MonthlyStipendModel(id: 1, isSelected: false, stipend: 2000),
    MonthlyStipendModel(id: 2, isSelected: false, stipend: 4000),
    MonthlyStipendModel(id: 3, isSelected: false, stipend: 6000),
    MonthlyStipendModel(id: 4, isSelected: false, stipend: 8000),
    MonthlyStipendModel(id: 5, isSelected: false, stipend: 100000)
];

List<CheckBoxModel> moreFiltersList = [
    CheckBoxModel(
        id: 1, isChecked: false, fieldName: "Internships with job offer"),
    CheckBoxModel(id: 2, isChecked: false, fieldName: "Fast response"),
    CheckBoxModel(id: 3, isChecked: false, fieldName: "Early applicant"),
    CheckBoxModel(id: 4, isChecked: false, fieldName: "Internships for women"),
];


List<CheckBoxModel> profilesList = [
  CheckBoxModel(id: 1, isChecked: false, fieldName: ".NET Development"),
  CheckBoxModel(id: 2, isChecked: false, fieldName: "Acting"),
  CheckBoxModel(id: 3, isChecked: false, fieldName: "3D Printing"),
  CheckBoxModel(id: 4, isChecked: false, fieldName: "Administration Intern"),
  CheckBoxModel(
      id: 5, isChecked: false, fieldName: "Administration Intern (Remote)"),
  CheckBoxModel(
      id: 6, isChecked: false, fieldName: "Android App Development Intern"),
  CheckBoxModel(
      id: 7, isChecked: false, fieldName: "Product Management Intern"),
  CheckBoxModel(id: 8, isChecked: false, fieldName: "Brand Management Intern"),
  CheckBoxModel(
      id: 9, isChecked: false, fieldName: "Business Analytics Intern"),
  CheckBoxModel(id: 10, isChecked: false, fieldName: "Data Science Intern"),
  CheckBoxModel(id: 11, isChecked: false, fieldName: "Accounting"),
  CheckBoxModel(id: 12, isChecked: false, fieldName: "Animation"),
  CheckBoxModel(id: 13, isChecked: false, fieldName: "Artificial Intelligence"),
  CheckBoxModel(id: 14, isChecked: false, fieldName: "Banking"),
  CheckBoxModel(id: 15, isChecked: false, fieldName: "Big Data"),
  CheckBoxModel(id: 16, isChecked: false, fieldName: "Biotechnology"),
  CheckBoxModel(id: 17, isChecked: false, fieldName: "Blockchain"),
  CheckBoxModel(id: 18, isChecked: false, fieldName: "Business Development"),
  CheckBoxModel(id: 19, isChecked: false, fieldName: "Chemistry"),
  CheckBoxModel(id: 20, isChecked: false, fieldName: "Civil Engineering"),
  CheckBoxModel(id: 21, isChecked: false, fieldName: "Content Writing"),
  CheckBoxModel(id: 22, isChecked: false, fieldName: "Cybersecurity"),
  CheckBoxModel(id: 23, isChecked: false, fieldName: "Data Analysis"),
  CheckBoxModel(id: 24, isChecked: false, fieldName: "Data Engineering"),
  CheckBoxModel(id: 25, isChecked: false, fieldName: "Data Science"),
  CheckBoxModel(id: 26, isChecked: false, fieldName: "Deep Learning"),
  CheckBoxModel(id: 27, isChecked: false, fieldName: "Digital Marketing"),
  CheckBoxModel(id: 28, isChecked: false, fieldName: "E-commerce"),
  CheckBoxModel(id: 29, isChecked: false, fieldName: "Economics"),
  CheckBoxModel(id: 30, isChecked: false, fieldName: "Education"),
  CheckBoxModel(id: 31, isChecked: false, fieldName: "Electrical Engineering"),
  CheckBoxModel(id: 32, isChecked: false, fieldName: "Electronics"),
  CheckBoxModel(id: 33, isChecked: false, fieldName: "Entrepreneurship"),
  CheckBoxModel(id: 34, isChecked: false, fieldName: "Environmental Science"),
  CheckBoxModel(id: 35, isChecked: false, fieldName: "Fashion Design"),
  CheckBoxModel(id: 36, isChecked: false, fieldName: "Finance"),
  CheckBoxModel(id: 37, isChecked: false, fieldName: "Game Development"),
  CheckBoxModel(id: 38, isChecked: false, fieldName: "Genetics"),
  CheckBoxModel(id: 39, isChecked: false, fieldName: "Graphic Design"),
  CheckBoxModel(id: 40, isChecked: false, fieldName: "Healthcare"),
  CheckBoxModel(id: 41, isChecked: false, fieldName: "Human Resources"),
  CheckBoxModel(id: 42, isChecked: false, fieldName: "Industrial Design"),
  CheckBoxModel(id: 43, isChecked: false, fieldName: "Information Technology"),
  CheckBoxModel(id: 44, isChecked: false, fieldName: "Interior Design"),
  CheckBoxModel(id: 45, isChecked: false, fieldName: "International Business"),
  CheckBoxModel(id: 46, isChecked: false, fieldName: "Investment Banking"),
  CheckBoxModel(id: 47, isChecked: false, fieldName: "Journalism"),
  CheckBoxModel(id: 48, isChecked: false, fieldName: "Law"),
  CheckBoxModel(id: 49, isChecked: false, fieldName: "Machine Learning"),
  CheckBoxModel(id: 50, isChecked: false, fieldName: "Manufacturing"),
  CheckBoxModel(id: 51, isChecked: false, fieldName: "Marketing"),
  CheckBoxModel(id: 52, isChecked: false, fieldName: "Material Science"),
  CheckBoxModel(id: 53, isChecked: false, fieldName: "Mathematics"),
  CheckBoxModel(id: 54, isChecked: false, fieldName: "Mechanical Engineering"),
  CheckBoxModel(id: 55, isChecked: false, fieldName: "Medicine"),
  CheckBoxModel(id: 56, isChecked: false, fieldName: "Mobile App Development"),
  CheckBoxModel(id: 57, isChecked: false, fieldName: "Nanotechnology"),
  CheckBoxModel(id: 58, isChecked: false, fieldName: "Network Engineering"),
  CheckBoxModel(id: 59, isChecked: false, fieldName: "Operations"),
  CheckBoxModel(id: 60, isChecked: false, fieldName: "Pharmaceuticals"),
  CheckBoxModel(id: 61, isChecked: false, fieldName: "Physics"),
  CheckBoxModel(id: 62, isChecked: false, fieldName: "Political Science"),
  CheckBoxModel(id: 63, isChecked: false, fieldName: "Product Design"),
  CheckBoxModel(id: 64, isChecked: false, fieldName: "Project Management"),
  CheckBoxModel(id: 65, isChecked: false, fieldName: "Psychology"),
  CheckBoxModel(id: 66, isChecked: false, fieldName: "Public Relations"),
  CheckBoxModel(id: 67, isChecked: false, fieldName: "Research"),
  CheckBoxModel(id: 68, isChecked: false, fieldName: "Robotics"),
  CheckBoxModel(id: 69, isChecked: false, fieldName: "Sales"),
  CheckBoxModel(id: 70, isChecked: false, fieldName: "Social Media Marketing"),
  CheckBoxModel(id: 71, isChecked: false, fieldName: "Software Development"),
  CheckBoxModel(id: 72, isChecked: false, fieldName: "Statistics"),
  CheckBoxModel(id: 73, isChecked: false, fieldName: "Supply Chain Management"),
  CheckBoxModel(id: 74, isChecked: false, fieldName: "Telecommunications"),
  CheckBoxModel(id: 75, isChecked: false, fieldName: "Textile Engineering"),
  CheckBoxModel(id: 76, isChecked: false, fieldName: "Tourism"),
  CheckBoxModel(id: 77, isChecked: false, fieldName: "UI/UX Design"),
  CheckBoxModel(id: 78, isChecked: false, fieldName: "Video Editing"),
  CheckBoxModel(id: 79, isChecked: false, fieldName: "Web Development"),
  CheckBoxModel(id: 80, isChecked: false, fieldName: "Zoology"),
  CheckBoxModel(id: 81, isChecked: false, fieldName: "Administration Intern"),
  CheckBoxModel(
      id: 82, isChecked: false, fieldName: "Administration Intern (Remote)"),
  CheckBoxModel(
      id: 83, isChecked: false, fieldName: "Android App Development Intern"),
  CheckBoxModel(
      id: 84, isChecked: false, fieldName: "Product Management Intern"),
  CheckBoxModel(id: 85, isChecked: false, fieldName: "Brand Management Intern"),
  CheckBoxModel(
      id: 86, isChecked: false, fieldName: "Business Analytics Intern"),
  CheckBoxModel(id: 87, isChecked: false, fieldName: "Data Science Intern"),
  CheckBoxModel(id: 88, isChecked: false, fieldName: "Brand Management Intern"),
  CheckBoxModel(
      id: 89, isChecked: false, fieldName: "Administration Intern (Remote)"),
  CheckBoxModel(id: 90, isChecked: false, fieldName: "Data Science Intern"),
];

List<CheckBoxModel> citiesList = [
  CheckBoxModel(id: 1, isChecked: false, fieldName: "Mumbai"),
  CheckBoxModel(id: 2, isChecked: false, fieldName: "Delhi"),
  CheckBoxModel(id: 3, isChecked: false, fieldName: "Bengaluru"),
  CheckBoxModel(id: 4, isChecked: false, fieldName: "Hyderabad"),
  CheckBoxModel(id: 5, isChecked: false, fieldName: "Ahmedabad"),
  CheckBoxModel(id: 6, isChecked: false, fieldName: "Chennai"),
  CheckBoxModel(id: 7, isChecked: false, fieldName: "Kolkata"),
  CheckBoxModel(id: 8, isChecked: false, fieldName: "Surat"),
  CheckBoxModel(id: 9, isChecked: false, fieldName: "Pune"),
  CheckBoxModel(id: 10, isChecked: false, fieldName: "Jaipur"),
  CheckBoxModel(id: 11, isChecked: false, fieldName: "Lucknow"),
  CheckBoxModel(id: 12, isChecked: false, fieldName: "Kanpur"),
  CheckBoxModel(id: 13, isChecked: false, fieldName: "Nagpur"),
  CheckBoxModel(id: 14, isChecked: false, fieldName: "Indore"),
  CheckBoxModel(id: 15, isChecked: false, fieldName: "Thane"),
  CheckBoxModel(id: 16, isChecked: false, fieldName: "Bhopal"),
  CheckBoxModel(id: 17, isChecked: false, fieldName: "Visakhapatnam"),
  CheckBoxModel(id: 18, isChecked: false, fieldName: "Pimpri-Chinchwad"),
  CheckBoxModel(id: 19, isChecked: false, fieldName: "Patna"),
  CheckBoxModel(id: 20, isChecked: false, fieldName: "Vadodara"),
  CheckBoxModel(id: 21, isChecked: false, fieldName: "Ghaziabad"),
  CheckBoxModel(id: 22, isChecked: false, fieldName: "Ludhiana"),
  CheckBoxModel(id: 23, isChecked: false, fieldName: "Agra"),
  CheckBoxModel(id: 24, isChecked: false, fieldName: "Nashik"),
  CheckBoxModel(id: 25, isChecked: false, fieldName: "Faridabad"),
  CheckBoxModel(id: 26, isChecked: false, fieldName: "Meerut"),
  CheckBoxModel(id: 27, isChecked: false, fieldName: "Rajkot"),
  CheckBoxModel(id: 28, isChecked: false, fieldName: "Kalyan-Dombivli"),
  CheckBoxModel(id: 29, isChecked: false, fieldName: "Vasai-Virar"),
  CheckBoxModel(id: 30, isChecked: false, fieldName: "Varanasi"),
  CheckBoxModel(id: 31, isChecked: false, fieldName: "Srinagar"),
  CheckBoxModel(id: 32, isChecked: false, fieldName: "Aurangabad"),
  CheckBoxModel(id: 33, isChecked: false, fieldName: "Dhanbad"),
  CheckBoxModel(id: 34, isChecked: false, fieldName: "Amritsar"),
  CheckBoxModel(id: 35, isChecked: false, fieldName: "Navi Mumbai"),
  CheckBoxModel(id: 36, isChecked: false, fieldName: "Allahabad"),
  CheckBoxModel(id: 37, isChecked: false, fieldName: "Howrah"),
  CheckBoxModel(id: 38, isChecked: false, fieldName: "Ranchi"),
  CheckBoxModel(id: 39, isChecked: false, fieldName: "Gwalior"),
  CheckBoxModel(id: 40, isChecked: false, fieldName: "Jabalpur"),
  CheckBoxModel(id: 41, isChecked: false, fieldName: "Coimbatore"),
  CheckBoxModel(id: 42, isChecked: false, fieldName: "Vijayawada"),
  CheckBoxModel(id: 43, isChecked: false, fieldName: "Jodhpur"),
  CheckBoxModel(id: 44, isChecked: false, fieldName: "Madurai"),
  CheckBoxModel(id: 45, isChecked: false, fieldName: "Raipur"),
  CheckBoxModel(id: 46, isChecked: false, fieldName: "Kota"),
  CheckBoxModel(id: 47, isChecked: false, fieldName: "Chandigarh"),
  CheckBoxModel(id: 48, isChecked: false, fieldName: "Guwahati"),
  CheckBoxModel(id: 49, isChecked: false, fieldName: "Solapur"),
  CheckBoxModel(id: 50, isChecked: false, fieldName: "Hubli-Dharwad"),
  CheckBoxModel(id: 51, isChecked: false, fieldName: "Mysore"),
  CheckBoxModel(id: 52, isChecked: false, fieldName: "Tiruchirappalli"),
  CheckBoxModel(id: 53, isChecked: false, fieldName: "Bareilly"),
  CheckBoxModel(id: 54, isChecked: false, fieldName: "Aligarh"),
  CheckBoxModel(id: 55, isChecked: false, fieldName: "Tiruppur"),
  CheckBoxModel(id: 56, isChecked: false, fieldName: "Moradabad"),
  CheckBoxModel(id: 57, isChecked: false, fieldName: "Bhiwandi"),
  CheckBoxModel(id: 58, isChecked: false, fieldName: "Saharanpur"),
  CheckBoxModel(id: 59, isChecked: false, fieldName: "Guntur"),
  CheckBoxModel(id: 60, isChecked: false, fieldName: "Amravati"),
  CheckBoxModel(id: 61, isChecked: false, fieldName: "Bikaner"),
  CheckBoxModel(id: 62, isChecked: false, fieldName: "Noida"),
  CheckBoxModel(id: 63, isChecked: false, fieldName: "Jamshedpur"),
  CheckBoxModel(id: 64, isChecked: false, fieldName: "Bhilai"),
  CheckBoxModel(id: 65, isChecked: false, fieldName: "Cuttack"),
  CheckBoxModel(id: 66, isChecked: false, fieldName: "Firozabad"),
  CheckBoxModel(id: 67, isChecked: false, fieldName: "Kochi"),
  CheckBoxModel(id: 68, isChecked: false, fieldName: "Bhavnagar"),
  CheckBoxModel(id: 69, isChecked: false, fieldName: "Dehradun"),
  CheckBoxModel(id: 70, isChecked: false, fieldName: "Durgapur"),
  CheckBoxModel(id: 71, isChecked: false, fieldName: "Asansol"),
  CheckBoxModel(id: 72, isChecked: false, fieldName: "Nanded"),
  CheckBoxModel(id: 73, isChecked: false, fieldName: "Kolhapur"),
  CheckBoxModel(id: 74, isChecked: false, fieldName: "Ajmer"),
  CheckBoxModel(id: 75, isChecked: false, fieldName: "Gulbarga"),
  CheckBoxModel(id: 76, isChecked: false, fieldName: "Jamnagar"),
  CheckBoxModel(id: 77, isChecked: false, fieldName: "Ujjain"),
  CheckBoxModel(id: 78, isChecked: false, fieldName: "Loni"),
  CheckBoxModel(id: 79, isChecked: false, fieldName: "Siliguri"),
  CheckBoxModel(id: 80, isChecked: false, fieldName: "Jhansi"),
  CheckBoxModel(id: 81, isChecked: false, fieldName: "Ulhasnagar"),
  CheckBoxModel(id: 82, isChecked: false, fieldName: "Nellore"),
  CheckBoxModel(id: 83, isChecked: false, fieldName: "Jammu"),
  CheckBoxModel(id: 84, isChecked: false, fieldName: "Sangli-Miraj & Kupwad"),
  CheckBoxModel(id: 85, isChecked: false, fieldName: "Belgaum"),
  CheckBoxModel(id: 86, isChecked: false, fieldName: "Mangalore"),
  CheckBoxModel(id: 87, isChecked: false, fieldName: "Ambattur"),
  CheckBoxModel(id: 88, isChecked: false, fieldName: "Tirunelveli"),
  CheckBoxModel(id: 89, isChecked: false, fieldName: "Malegaon"),
  CheckBoxModel(id: 90, isChecked: false, fieldName: "Gaya"),
  CheckBoxModel(id: 91, isChecked: false, fieldName: "Jalgaon"),
  CheckBoxModel(id: 92, isChecked: false, fieldName: "Udaipur"),
  CheckBoxModel(id: 93, isChecked: false, fieldName: "Maheshtala"),
  CheckBoxModel(id: 94, isChecked: false, fieldName: "Davanagere"),
  CheckBoxModel(id: 95, isChecked: false, fieldName: "Kozhikode"),
  CheckBoxModel(id: 96, isChecked: false, fieldName: "Kurnool"),
  CheckBoxModel(id: 97, isChecked: false, fieldName: "Rajahmundry"),
  CheckBoxModel(id: 98, isChecked: false, fieldName: "Bokaro Steel City"),
  CheckBoxModel(id: 99, isChecked: false, fieldName: "South Dumdum"),
  CheckBoxModel(id: 100, isChecked: false, fieldName: "Bellary"),
  CheckBoxModel(id: 101, isChecked: false, fieldName: "Patiala"),
  CheckBoxModel(id: 102, isChecked: false, fieldName: "Gopalpur"),
  CheckBoxModel(id: 103, isChecked: false, fieldName: "Agartala"),
  CheckBoxModel(id: 104, isChecked: false, fieldName: "Bhagalpur"),
  CheckBoxModel(id: 105, isChecked: false, fieldName: "Muzaffarnagar"),
  CheckBoxModel(id: 106, isChecked: false, fieldName: "Bhatpara"),
  CheckBoxModel(id: 107, isChecked: false, fieldName: "Panihati"),
  CheckBoxModel(id: 108, isChecked: false, fieldName: "Latur"),
  CheckBoxModel(id: 109, isChecked: false, fieldName: "Dhule"),
  CheckBoxModel(id: 110, isChecked: false, fieldName: "Rohtak"),
  CheckBoxModel(id: 111, isChecked: false, fieldName: "Korba"),
  CheckBoxModel(id: 112, isChecked: false, fieldName: "Bhilwara"),
  CheckBoxModel(id: 113, isChecked: false, fieldName: "Brahmapur"),
  CheckBoxModel(id: 114, isChecked: false, fieldName: "Muzaffarpur"),
  CheckBoxModel(id: 115, isChecked: false, fieldName: "Ahmednagar"),
  CheckBoxModel(id: 116, isChecked: false, fieldName: "Mathura"),
  CheckBoxModel(id: 117, isChecked: false, fieldName: "Kollam"),
  CheckBoxModel(id: 118, isChecked: false, fieldName: "Avadi"),
  CheckBoxModel(id: 119, isChecked: false, fieldName: "Rajpur Sonarpur"),
  CheckBoxModel(id: 120, isChecked: false, fieldName: "Kadapa"),
];
